---
name: "Power profile submission"
description: "Providing new measurements to the library"
labels: "new-power-profile"
body:
- type: markdown
  attributes:
    value: Awesome you are extending the Powercalc library! Please answer the questions and checklist. Thanks.
- type: textarea
  attributes:
    label: "HA Device information"
    description: "Provide the device information. This can be found on the device page in HA, on the top left under `Device Info`. Please paste that information here."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Further device information"
    description: "Provide and links and additional information about the device you are adding in this PR."
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have created a single PR per device. When you have multiple submissions please create separate PR's.
        required: true
      - label: For lights - I have only included the gzipped files (*.gz), not the raw CSV files.
      - label: For lights - I have provided a CSV file per supported color mode. Look that up in Developer Tools -> States
- type: textarea
  attributes:
    label: "Additional info"
