name: Lint

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Powercalc
        uses: actions/checkout@master
      - name: Run MyPy
        uses: jpetrucciani/mypy-check@master
        with:
          path: './custom_components/powercalc'
          requirements: voluptuous-stubs homeassistant-stubs numpy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Powercalc
        uses: actions/checkout@v3
      - name: Run Ruff
        uses: chartboost/ruff-action@v1
        with:
          src: './custom_components/powercalc'